# Generated by Django 5.1.4 on 2024-12-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_hire_date_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_hr',
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('E', 'Employee'), ('H', 'HR Manager'), ('A', 'Admin')], default='E', max_length=1),
        ),
    ]
