# Generated by Django 5.1.4 on 2024-12-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_employee_is_hr_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('E', 'Employee'), ('H', 'HR Manager'), ('A', 'Admin')], max_length=1),
        ),
    ]
