# Generated by Django 5.1.4 on 2024-12-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_review_period_start_performanceanalysis_month_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceanalysis',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
